
package mtlStub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecordManagerMTLImplService", targetNamespace = "http://servers", wsdlLocation = "http://localhost:8080/DCMS3/services/RecordManagerMTLImpl?wsdl")
public class RecordManagerMTLImplService
    extends Service
{

    private final static URL RECORDMANAGERMTLIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECORDMANAGERMTLIMPLSERVICE_EXCEPTION;
    private final static QName RECORDMANAGERMTLIMPLSERVICE_QNAME = new QName("http://servers", "RecordManagerMTLImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DCMS3/services/RecordManagerMTLImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECORDMANAGERMTLIMPLSERVICE_WSDL_LOCATION = url;
        RECORDMANAGERMTLIMPLSERVICE_EXCEPTION = e;
    }

    public RecordManagerMTLImplService() {
        super(__getWsdlLocation(), RECORDMANAGERMTLIMPLSERVICE_QNAME);
    }

    public RecordManagerMTLImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECORDMANAGERMTLIMPLSERVICE_QNAME, features);
    }

    public RecordManagerMTLImplService(URL wsdlLocation) {
        super(wsdlLocation, RECORDMANAGERMTLIMPLSERVICE_QNAME);
    }

    public RecordManagerMTLImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECORDMANAGERMTLIMPLSERVICE_QNAME, features);
    }

    public RecordManagerMTLImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecordManagerMTLImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecordManagerMTLImpl
     */
    @WebEndpoint(name = "RecordManagerMTLImpl")
    public RecordManagerMTLImpl getRecordManagerMTLImpl() {
        return super.getPort(new QName("http://servers", "RecordManagerMTLImpl"), RecordManagerMTLImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecordManagerMTLImpl
     */
    @WebEndpoint(name = "RecordManagerMTLImpl")
    public RecordManagerMTLImpl getRecordManagerMTLImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://servers", "RecordManagerMTLImpl"), RecordManagerMTLImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECORDMANAGERMTLIMPLSERVICE_EXCEPTION!= null) {
            throw RECORDMANAGERMTLIMPLSERVICE_EXCEPTION;
        }
        return RECORDMANAGERMTLIMPLSERVICE_WSDL_LOCATION;
    }

}
