package corba;


/**
* corba/RecordManagerCORBA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Progs/Java-Progs/comp6231/src/corba/RecordManagerCORBA.idl
* Saturday, June 9, 2018 10:43:39 PM EDT
*/

public interface RecordManagerCORBA extends RecordManagerCORBAOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RecordManagerCORBA
