package corba;


/**
* corba/RecordManagerCORBAOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Progs/Java-Progs/comp6231/src/corba/RecordManager.idl
* Friday, June 8, 2018 2:59:24 PM EDT
*/

public interface RecordManagerCORBAOperations 
{
  boolean createTRecord (String firstName, String lastName, String address, String phoneNumber, String specialization, String location, String callerId);
  boolean createSRecord (String firstName, String lastName, String coursesRegistred, boolean status, String statusDate, String callerId);
  String getRecordCounts (String callerId);
  boolean editRecord (String recordID, String fieldName, String newValue, String callerId);
  boolean recordExist (String recordId);
  void shutdown ();
} // interface RecordManagerCORBAOperations
