package corba;


/**
* corba/RecordManagerCORBAOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Progs/Java-Progs/comp6231/src/corba/RecordManager.idl
* Friday, June 8, 2018 3:40:42 AM EDT
*/

public interface RecordManagerCORBAOperations 
{
  boolean createTRecord (String firstName, String lastName, String address, int phoneNumber, org.omg.CORBA.Object specialization, String location, String callerId);
  boolean createSRecord (String firstName, String lastName, org.omg.CORBA.Object coursesRegistred, boolean status, String statusDate, String callerId);
  String getRecordCounts (String callerId);
  int getLocalRecordsCount (String callerId);
  boolean editRecord (String recordID, String fieldName, org.omg.CORBA.Object newValue, String callerId);
  boolean recordExist (String recordId);
  void shutdown ();
} // interface RecordManagerCORBAOperations
