package corba;


/**
* corba/StrList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Progs/Java-Progs/comp6231/src/corba/RecordManager.idl
* Friday, June 8, 2018 3:57:02 AM EDT
*/

public final class StrList implements org.omg.CORBA.portable.IDLEntity
{
  public String str = null;

  public StrList ()
  {
  } // ctor

  public StrList (String _str)
  {
    str = _str;
  } // ctor

} // class StrList
