package corba;

/**
* corba/StrListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Progs/Java-Progs/comp6231/src/corba/RecordManager.idl
* Friday, June 8, 2018 3:57:02 AM EDT
*/

public final class StrListHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.StrList value = null;

  public StrListHolder ()
  {
  }

  public StrListHolder (corba.StrList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.StrListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.StrListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.StrListHelper.type ();
  }

}
