package corba;


/**
* corba/strListsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Progs/Java-Progs/comp6231/src/corba/RecordManager.idl
* Friday, June 8, 2018 3:57:02 AM EDT
*/

abstract public class strListsHelper
{
  private static String  _id = "IDL:corba/strLists:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.StrList[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.StrList[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = corba.StrListHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (corba.strListsHelper.id (), "strLists", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.StrList[] read (org.omg.CORBA.portable.InputStream istream)
  {
    corba.StrList value[] = null;
    int _len0 = istream.read_long ();
    value = new corba.StrList[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = corba.StrListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.StrList[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      corba.StrListHelper.write (ostream, value[_i0]);
  }

}
