
package ddoStub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecordManagerDDOImplService", targetNamespace = "http://servers", wsdlLocation = "http://localhost:8080/DCMS3/services/RecordManagerDDOImpl?wsdl")
public class RecordManagerDDOImplService
    extends Service
{

    private final static URL RECORDMANAGERDDOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECORDMANAGERDDOIMPLSERVICE_EXCEPTION;
    private final static QName RECORDMANAGERDDOIMPLSERVICE_QNAME = new QName("http://servers", "RecordManagerDDOImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DCMS3/services/RecordManagerDDOImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECORDMANAGERDDOIMPLSERVICE_WSDL_LOCATION = url;
        RECORDMANAGERDDOIMPLSERVICE_EXCEPTION = e;
    }

    public RecordManagerDDOImplService() {
        super(__getWsdlLocation(), RECORDMANAGERDDOIMPLSERVICE_QNAME);
    }

    public RecordManagerDDOImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECORDMANAGERDDOIMPLSERVICE_QNAME, features);
    }

    public RecordManagerDDOImplService(URL wsdlLocation) {
        super(wsdlLocation, RECORDMANAGERDDOIMPLSERVICE_QNAME);
    }

    public RecordManagerDDOImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECORDMANAGERDDOIMPLSERVICE_QNAME, features);
    }

    public RecordManagerDDOImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecordManagerDDOImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecordManagerDDOImpl
     */
    @WebEndpoint(name = "RecordManagerDDOImpl")
    public RecordManagerDDOImpl getRecordManagerDDOImpl() {
        return super.getPort(new QName("http://servers", "RecordManagerDDOImpl"), RecordManagerDDOImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecordManagerDDOImpl
     */
    @WebEndpoint(name = "RecordManagerDDOImpl")
    public RecordManagerDDOImpl getRecordManagerDDOImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://servers", "RecordManagerDDOImpl"), RecordManagerDDOImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECORDMANAGERDDOIMPLSERVICE_EXCEPTION!= null) {
            throw RECORDMANAGERDDOIMPLSERVICE_EXCEPTION;
        }
        return RECORDMANAGERDDOIMPLSERVICE_WSDL_LOCATION;
    }

}
