package frontEnd;


/**
* frontEnd/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Progs/Java-Progs/comp6231/src/frontEnd/FrontEnd.idl
* Sunday, July 15, 2018 9:35:29 PM EDT
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
