package frontEnd;


/**
* frontEnd/FrontEndPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Progs/Java-Progs/comp6231/src/frontEnd/FrontEnd.idl
* Sunday, July 15, 2018 9:35:29 PM EDT
*/

public abstract class FrontEndPOA extends org.omg.PortableServer.Servant
 implements frontEnd.FrontEndOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createTRecord", new java.lang.Integer (0));
    _methods.put ("createSRecord", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("recordExist", new java.lang.Integer (4));
    _methods.put ("transferRecord", new java.lang.Integer (5));
    _methods.put ("shutdown", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // frontEnd/FrontEnd/createTRecord
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phoneNumber = in.read_string ();
         String specialization = in.read_string ();
         String location = in.read_string ();
         String managerId = in.read_string ();
         boolean $result = false;
         $result = this.createTRecord (firstName, lastName, address, phoneNumber, specialization, location, managerId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // frontEnd/FrontEnd/createSRecord
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String coursesRegistred = in.read_string ();
         boolean status = in.read_boolean ();
         String statusDate = in.read_string ();
         String managerId = in.read_string ();
         boolean $result = false;
         $result = this.createSRecord (firstName, lastName, coursesRegistred, status, statusDate, managerId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // frontEnd/FrontEnd/getRecordCounts
       {
         String managerId = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (managerId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // frontEnd/FrontEnd/editRecord
       {
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String managerId = in.read_string ();
         boolean $result = false;
         $result = this.editRecord (recordID, fieldName, newValue, managerId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // frontEnd/FrontEnd/recordExist
       {
         String recordId = in.read_string ();
         String managerId = in.read_string ();
         boolean $result = false;
         $result = this.recordExist (recordId, managerId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // frontEnd/FrontEnd/transferRecord
       {
         String managerId = in.read_string ();
         String recordId = in.read_string ();
         String remoteCenterServerName = in.read_string ();
         boolean $result = false;
         $result = this.transferRecord (managerId, recordId, remoteCenterServerName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // frontEnd/FrontEnd/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:frontEnd/FrontEnd:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FrontEnd _this() 
  {
    return FrontEndHelper.narrow(
    super._this_object());
  }

  public FrontEnd _this(org.omg.CORBA.ORB orb) 
  {
    return FrontEndHelper.narrow(
    super._this_object(orb));
  }


} // class FrontEndPOA
