
package lvlStub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecordManagerLVLImplService", targetNamespace = "http://servers", wsdlLocation = "http://localhost:8080/DCMS3/services/RecordManagerLVLImpl?wsdl")
public class RecordManagerLVLImplService
    extends Service
{

    private final static URL RECORDMANAGERLVLIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECORDMANAGERLVLIMPLSERVICE_EXCEPTION;
    private final static QName RECORDMANAGERLVLIMPLSERVICE_QNAME = new QName("http://servers", "RecordManagerLVLImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DCMS3/services/RecordManagerLVLImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECORDMANAGERLVLIMPLSERVICE_WSDL_LOCATION = url;
        RECORDMANAGERLVLIMPLSERVICE_EXCEPTION = e;
    }

    public RecordManagerLVLImplService() {
        super(__getWsdlLocation(), RECORDMANAGERLVLIMPLSERVICE_QNAME);
    }

    public RecordManagerLVLImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECORDMANAGERLVLIMPLSERVICE_QNAME, features);
    }

    public RecordManagerLVLImplService(URL wsdlLocation) {
        super(wsdlLocation, RECORDMANAGERLVLIMPLSERVICE_QNAME);
    }

    public RecordManagerLVLImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECORDMANAGERLVLIMPLSERVICE_QNAME, features);
    }

    public RecordManagerLVLImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecordManagerLVLImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecordManagerLVLImpl
     */
    @WebEndpoint(name = "RecordManagerLVLImpl")
    public RecordManagerLVLImpl getRecordManagerLVLImpl() {
        return super.getPort(new QName("http://servers", "RecordManagerLVLImpl"), RecordManagerLVLImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecordManagerLVLImpl
     */
    @WebEndpoint(name = "RecordManagerLVLImpl")
    public RecordManagerLVLImpl getRecordManagerLVLImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://servers", "RecordManagerLVLImpl"), RecordManagerLVLImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECORDMANAGERLVLIMPLSERVICE_EXCEPTION!= null) {
            throw RECORDMANAGERLVLIMPLSERVICE_EXCEPTION;
        }
        return RECORDMANAGERLVLIMPLSERVICE_WSDL_LOCATION;
    }

}
